spring:
  application:
    name: dubbo-hmily-tcc-consumer
  main:
    allow-bean-definition-overriding: true
    web-application-type: none
dubbo:
  scan:
    base-packages: com.linyuan.jeektime.dubbohmilytccconsumer
  registry:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181
  consumer:
    retries: 0
